### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ChairsDaily** [marcelgarus/factorize#3]
Ive been studying number theory and have some extremely efficient functions to add. I exercise best practice and will conform with your docstrings and general API conventions. A collab would be a lot of fun. Im going to make some pull requests, give them thought Ill be online tomorrow. :grin:

**Comment by MarcelGarus** [comment]
Nice, I'm looking forward to it 😊 Thanks in advance

**Comment by ChairsDaily** [comment]
How would you feel about a static **option** for for factorization? I have a few factorizers that are extremely fast for N < 20 digits, and some divide and conquers that can handle loads of up to 150 digits. maybe a command line flag '--static' that forces pre-calculation instead of dynamic generation? Generators would still be used because they are faster to write to, however it would be tuple() or list() before return.

**Comment by ChairsDaily** [comment]
This is your current prime generator over `10^5`
```
10 loops, best of 3: 70.7 msec per loop
```
My proposed (heavily modified) Sieve of Eratosthenes does this in 
```
100 loops, best of 3: 5.65 msec per loop
```
Granted my model has a strict upper bound of performance, at around 10**10 because
of memory limitations. If you use it as a generator, however, it has no limits.

**Comment by ChairsDaily** [comment]
you adopt a dynamic method for factorization, but for large N > 10^20 it fails, therefore I propose using a static method that does wheel factorization mod 6 over N < 10^30, otherwise using Pollard Rho's composite factor algorithm (expresses a number as the sum of squares approach N until the GCD of the difference of both candidates and N is greater than a specified minimum (a moderately small prime, 29 well say)) to pull a factor, and perform wheel mod 6 over each one returning a final factorization of N / p and p where p is Pollard's composite. I will also implement an extremely fast primality test based on Miller and Rabins work using predefined compositeness witnesses. this will be used to check the status of Pollards composite (it fails sometimes, its probabilistic which is why it will run N / f times where f is fermats number as derived from N) before beginning wheel factorization.  this makes for a reasonably quick test of numbers like
11112473647372747228411848381773

**Comment by ChairsDaily** [comment]
note Pythons rounding flaw. huge integers are default expressed as 1.338483E+18 or something, so after factorizing huge N if u multiply youll be a couple million off but a division test will show that the result is correct

**Comment by ChairsDaily** [comment]
ill have a pull req. for the primality test before days end

**Comment by MarcelGarus** [comment]
Wow, I didn't understand much of the first comment (yet), but I'm always looking forward to learning new math. I'm really looking forward to your PR.

> note Pythons rounding flaw

Are you sure that's an issue that also applies to integers, not just to floats? From [this Python Enhancement Proposal](https://www.python.org/dev/peps/pep-0237/#implementation) it sure looks like numbers store all the digits arbitrarily precise. The same topic is discussed [here on StackOverflow](https://stackoverflow.com/a/20980470/3102005).
